#!/usr/bin/env python3
"""
Generates src/webhook_config.h from a plain Discord webhook URL, XOR-
obfuscated with the same fixed key report.cpp decodes with at runtime (see
kWebhookXorKey in src/report.cpp -- keep KEY below in sync with that one if
you ever change it).

This is NOT encryption and isn't meant to be -- it only keeps the URL from
showing up as one plain readable string in a `strings`/hex-editor pass over
the built DLL. Anyone stepping through the DLL in a debugger, or hooking
WinHttpConnect/WinHttpSendRequest, still sees the real URL the moment
DecodeWebhookUrl() reconstructs it in memory to make the request. See
report.h's header comment and HANDOFF_VfxSins.md for the fuller picture of
what this does and doesn't protect against.

Usage:
    python3 tools/generate_webhook_config.py "https://discord.com/api/webhooks/.../..." > src/webhook_config.h

Run from the repo root so the redirect lands in the right place. The
result is gitignored (src/webhook_config.h) -- never commit it.
"""
import sys

# Must match kWebhookXorKey in src/report.cpp exactly, byte for byte.
KEY = [0x5A, 0x3C, 0x91, 0x7E, 0x2D, 0xC8, 0x11]


def main():
    if len(sys.argv) != 2:
        print("usage: generate_webhook_config.py <discord-webhook-url>", file=sys.stderr)
        sys.exit(1)

    url = sys.argv[1]
    encoded = [b ^ KEY[i % len(KEY)] for i, b in enumerate(url.encode("ascii"))]

    print("#pragma once")
    print("#include <cstddef>")
    print()
    print("// ---------------------------------------------------------------------------")
    print("// Generated by tools/generate_webhook_config.py -- do not hand-edit.")
    print("// This file is gitignored (see .gitignore) and must never be committed. See")
    print("// webhook_config.example.h for the committed template/instructions this was")
    print("// produced from.")
    print("// ---------------------------------------------------------------------------")
    print("inline constexpr unsigned char kWebhookUrlXor[] = {")
    for i in range(0, len(encoded), 12):
        chunk = encoded[i:i + 12]
        print("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    print("};")
    print(f"inline constexpr size_t kWebhookUrlXorLen = {len(encoded)};")


if __name__ == "__main__":
    main()
